comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: caoxicheng/caoxicheng.github.io # [在此输入仓库]
    data-repo-id: R_kgDOHt-Pxw # [在此输入仓库 ID]
    data-category: Announcements # [在此输入分类名]
    data-category-id: DIC_kwDOHt-Px84CXPTp
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 0
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

logo:
  subtitle: '没想到我这样人也能改变世界'
  avatar: '[https://avatars.githubusercontent.com/u/45220715?v=4&size=64](/)'

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 博客 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: movie
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 影单
      url: /movie/
    #- id: social
    #  theme: '#F44336'
    #  icon: solar:chat-square-like-bold-duotone
    #  title: 社交
    #  url: /friends/
